on:
  push:
    paths:
      - borenstein2009.rmd

name: Render borenstein2009.rmd

jobs:
  render:
    name: Render borenstein2009.rmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install Inconsolata
        run: sudo apt-get install fonts-inconsolata
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install remotes
        run: Rscript -e 'install.packages("remotes")'
      - name: Install metafor
        run: Rscript -e 'remotes::install_github("wviechtb/metafor")'
      - name: Install poolr
        run: Rscript -e 'install.packages("poolr")'
      - name: Render borenstein2009.rmd
        run: Rscript -e 'rmarkdown::render("borenstein2009.rmd", clean=TRUE); print(warnings())'
      - name: Commit results
        run: |
          git config --local user.email "wvb@wvbauer.com"
          git config --local user.name "Wolfgang Viechtbauer"
          git commit borenstein2009.html -m 'Re-build borenstein2009.html' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
